### ISSUE TITLE
textbox.getTextarea not available in v0.0.2 release

### ISSUE THREAD

**Issue by jywarren** [justinmanley/Leaflet.Illustrate#11]
GH says there've been 44 commits since v0.0.2; would you consider doing another release so I can peg the version # in bower? Thanks!

**Comment by jywarren** [comment]
For now I've used the commit SHA instead of a version # in bower.

**Comment by manleyjster** [comment]
Ok, great. I'll take a look at it over the weekend. 44 commits is a lot, so it sounds like it may make sense to bump the version.

**Comment by jywarren** [comment]
super, thanks! no rush, just chipping away at stuff and trying to connect
the dots as I go about it.
