### ISSUE TITLE
Republish on npm with spritesheet-2x.png included

### ISSUE THREAD

**Issue by thataustin** [justinmanley/Leaflet.Illustrate#19]
I tried to do the following:

```
npm install leaflet-illustrate
require('leaflet-illustrate/dist/Leaflet.Illustrate.js')
require('leaflet-illustrate/dist/Leaflet.Illustrate.css')
```

I'm using webpack as a bundler in this case, and the css loader is failing because the dist folder pulled down from npm doesn't contain a spritesheet-2x.png, which Leaflet.Illustrate.css references.

Kind of makes the npm package a bit unusable.  I'd really appreciate an updated package so I can utilize NPM :beers:

**Comment by justinmanley** [comment]
Done - please give it a try now.
